// frontend/src/components/Elements/IncidentUpdate.vue
<template>
    <div class="col-12 mb-3 pb-2 border-bottom" role="alert">
        <span class="font-weight-bold text-capitalize" :class="{'text-success': update.type.toLowerCase()==='resolved', 'text-danger': update.type.toLowerCase()==='investigating', 'text-warning': update.type.toLowerCase()==='update'}">{{update.type}}</span>
        <span class="text-muted">- {{update.message}}
            <button v-if="admin" @click="delete_update(update)" type="button" class="close">
                <span aria-hidden="true">&times;</span>
            </button>
        </span>
        <span class="d-block small">{{ago(update.created_at)}} ago</span>
    </div>
</template>

<script>
  import Api from "@/API";

  export default {
    name: "IncidentUpdate",
    props: {
      update: {
        required: true
      },
      admin: {
        required: true
      }
    },
    methods: {
      async delete_update(update) {
        this.res = await Api.incident_update_delete(update)
        if (this.res.status === "success") {
          await this.loadUpdates()
        }
      },
    }
  }
</script>

<style scoped>

</style>

// react-frontend/src/components/IncidentUpdate.jsx
import React from "react";
// import API from "../config/API";
import DateUtils from "../utils/DateUtils";

const IncidentUpdate = ({ update, admin }) => {
  // async loadUpdates() {
  //   this.updates = await Api.incident_updates(this.incident)
  // }

  const deleteUpdate = (update) => {
    alert("Delete Incident:", update.incident);
    // const res = await API.incident_update_delete(update);
    // if (res.status === "success") {
    //   this.onUpdate();
    // }
  };

  return (
    <div className="col-12 mb-3 pb-2 border-bottom" role="alert">
      <span
        className={`
          font-weight-bold text-capitalize
          ${update.type.toLowerCase() === "resolved" ? "text-success" : ""}
          ${update.type.toLowerCase() === "investigating" ? "text-danger" : ""}
          ${update.type.toLowerCase() === "update" ? "text-warning" : ""}
        `}
      >
        {update.type}
      </span>
      <span className="text-muted">
        - {update.message}
        {admin && (
          <button
            onClick={deleteUpdate(update)}
            type="button"
            className="close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        )}
      </span>
      <span className="d-block small">
        {DateUtils.ago(update.created_at)} ago
      </span>
    </div>
  );
};

export default IncidentUpdate;
