// frontend/src/components/Index/MessageBlock.vue
<template>
    <div class="card shadow mb-4" role="alert">
      <div class="card-body pb-2">
        <h3 class="mb-3 font-weight-bold">{{message.title}}</h3>
        <span class="mb-2">{{message.description}}</span>
        <div class="col-12 mb-0">
          <div class="dates">
            <div class="start">
              <strong>STARTS</strong> {{niceDate(message.start_on)}}
              <span></span>
            </div>
            <div class="ends">
              <strong>ENDS</strong> {{niceDate(message.end_on)}}
            </div>
          </div>
        </div>

        </div>
    </div>
</template>

<script>
export default {
  name: 'MessageBlock',
    props: {
        message: {
            type: Object,
            required: true,
        }
    }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// react-frontend/src/components/MessageBlock.jsx
import React from "react";
import DateUtils from "../utils/DateUtils";

const MessageBlock = ({ message }) => {
  return (
    <div className="card shadow mb-4" role="alert">
      <div className="card-body pb-2">
        <h3 className="mb-3 font-weight-bold">{message.title}</h3>
        <span className="mb-2">{message.description}</span>
        <div className="col-12 mb-0">
          <div className="dates">
            <div className="start">
              <strong>STARTS</strong> {DateUtils.niceDate(message.start_on)}
              <span></span>
            </div>
            <div className="ends">
              <strong>ENDS</strong> {DateUtils.niceDate(message.end_on)}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MessageBlock;
