// frontend/src/components/Service/ServiceBlock.vue
<template>
    <div class="mb-md-4 mb-4">
        <div class="card index-chart" :class="{'expanded-service': expanded}">
            <div class="card-body">
                <div class="col-12">
                    <h4 class="mt-2">
                        <router-link :to="serviceLink(service)" class="d-inline-block text-truncate font-4" style="max-width: 65vw;" :in_service="service">{{service.name}}</router-link>
                        <span class="badge float-right" :class="{'bg-success': service.online, 'bg-danger': !service.online}">{{service.online ? "ONLINE" : "OFFLINE"}}</span>
                    </h4>

                    <ServiceTopStats :service="service"/>

                </div>
            </div>

            <div v-show="!expanded" v-observe-visibility="{callback: visibleChart, throttle: 200}" class="chart-container">
                <ServiceChart :service="service" :visible="visible" :chart_timeframe="chartTimeframe"/>
            </div>

            <div class="row lower_canvas full-col-12 text-white" :class="{'bg-success': service.online, 'bg-danger': !service.online}">
                <div class="col-md-10 col-6">
                    <div class="dropup" :class="{show: dropDownMenu}">
                        <button style="font-size: 10pt;" @click.prevent="openMenu('timeframe')" type="button" class="col-4 float-left btn btn-sm float-right btn-block text-white dropdown-toggle service_scale pr-2">
                            {{timeframepick.text}}
                        </button>
                        <div class="service-tm-menu" :class="{'d-none': !dropDownMenu}">
                            <a v-for="(timeframe, i) in timeframes" @click.prevent="changeTimeframe(timeframe)" class="dropdown-item" href="#" :class="{'active': timeframepick === timeframe}">{{timeframe.text}}</a>
                        </div>
                    </div>

                    <div class="dropup" :class="{show: intervalMenu}">
                        <button style="font-size: 10pt;" @click.prevent="openMenu('interval')" type="button" class="col-4 float-left btn btn-sm float-right btn-block text-white dropdown-toggle service_scale pr-2">
                            {{intervalpick.text}}
                        </button>
                        <div class="service-tm-menu" :class="{'d-none': !intervalMenu}">
                            <a v-for="(interval, i) in intervals" @click.prevent="changeInterval(interval)" class="dropdown-item" href="#" :class="{'active': intervalpick === interval, 'disabled': disabled_interval(interval)}">
                                {{interval.text}}
                            </a>
                        </div>

                        <span class="d-none float-left d-md-inline">
                            {{smallText(service)}}
                        </span>
                    </div>

                </div>


                <div class="col-md-2 col-6 float-right">
                    <router-link tag="button" v-if="!expanded" :to="serviceLink(service)" class="btn btn-sm float-right dyn-dark text-white" :class="{'bg-success': service.online, 'bg-danger': !service.online}">
                        {{$t('service.view')}}
                    </router-link>
                </div>
            </div>

        </div>
    </div>
</template>

<script>
const Analytics = () => import(/* webpackChunkName: "service" */ './Analytics');
const ServiceChart  = () => import(/* webpackChunkName: "service" */ "./ServiceChart");
const ServiceTopStats = () => import(/* webpackChunkName: "service" */ "@/components/Service/ServiceTopStats");

export default {
    name: 'ServiceBlock',
    components: { Analytics, ServiceTopStats, ServiceChart},
    props: {
        service: {
            type: Object,
            required: true
        },
    },
  computed: {
    timeframepick() {
      return this.timeframes.find(s => s.value === this.timeframe_val)
    },
    intervalpick() {
      return this.intervals.find(s => s.value === this.interval_val)
    },
    chartTimeframe() {
      return {start_time: this.timeframe_val, interval: this.interval_val}
    }
  },
    data() {
        return {
          timer_func: null,
            expanded: false,
            visible: false,
            dropDownMenu: false,
            intervalMenu: false,
          interval_val: "60m",
          timeframe_val: this.timeset(259200),
          timeframes: [
            {value: this.timeset(1800), text: "30 Minutes", set: 1},
            {value: this.timeset(3600), text: "1 Hour", set: 2},
            {value: this.timeset(21600), text: "6 Hours", set: 3},
            {value: this.timeset(43200), text: "12 Hours", set: 4},
            {value: this.timeset(86400), text: "1 Day", set: 5},
            {value: this.timeset(259200), text: "3 Days", set: 6},
            {value: this.timeset(604800), text: "7 Days", set: 7},
            {value: this.timeset(1209600), text: "14 Days", set: 8},
            {value: this.timeset(2592000), text: "1 Month", set: 9},
            {value: this.timeset(7776000), text: "3 Months", set: 10},
            {value: 0, text: "All Records"},
          ],
          intervals: [
            {value: "1m", text: "1/min", set: 1},
            {value: "5m", text: "5/min", set: 2},
            {value: "15m", text: "15/min", set: 3},
            {value: "30m", text: "30/min", set: 4 },
            {value: "60m", text: "1/hr", set: 5 },
            {value: "180m", text: "3/hr", set: 6 },
            {value: "360m", text: "6/hr", set: 7 },
            {value: "720m", text: "12/hr", set: 8 },
            {value: "1440m", text: "1/day", set: 9 },
            {value: "4320m", text: "3/day", set: 10 },
            {value: "10080m", text: "7/day", set: 11 },
          ],
          stats: {
                total_failures: {
                    title: "Total Failures",
                    subtitle: "Last 7 Days",
                    value: 0,
                },
                high_latency: {
                    title: "Highest Latency",
                    subtitle: "Last 7 Days",
                    value: 0,
                },
                lowest_latency: {
                    title: "Lowest Latency",
                    subtitle: "Last 7 Days",
                    value: 0,
                },
                high_ping: {
                    title: "Highest Ping",
                    subtitle: "Last 7 Days",
                    value: 0,
                },
                low_ping: {
                    title: "Lowest Ping",
                    subtitle: "Last 7 Days",
                    value: 0,
                }
            },
        }
    },
  beforeDestroy() {
    // clearInterval(this.timer_func)
  },
  created() {

  },
    methods: {
      disabled_interval(interval) {
        let min = this.timeframepick.set - interval.set - 1;
        return min >= interval.set;
      },
      timeset (seconds) {
        return this.toUnix(this.nowSubtract(seconds))
      },
      openMenu(tm) {
        if (tm === "interval") {
          this.intervalMenu = !this.intervalMenu
          this.dropDownMenu = false
        } else if (tm === "timeframe") {
          this.dropDownMenu = !this.dropDownMenu
          this.intervalMenu = false
        }
      },
      changeInterval(tm) {
        this.interval_val = tm.value
        this.intervalMenu = false
        this.dropDownMenu = false
      },
      changeTimeframe(tm) {
        this.timeframe_val = tm.value
        this.dropDownMenu = false
        this.intervalMenu = false
      },
        visibleChart(isVisible, entry) {
                if (isVisible && !this.visible) {
                    this.visible = true

                  // if (!this.timer_func) {
                  //   this.timer_func = setInterval(async () => {
                  //     this.track_service = await Api.service(this.service.id)
                  //   }, this.track_service.check_interval * 100)
                  // }
                }
        }
    }
}
</script>

// react-frontend/src/components/ServiceBlock.jsx
import React, { useState } from "react";
import { useHistory } from "react-router-dom";
import langs from "../config/langs";
import DateUtils from "../utils/DateUtils";
import ServiceChart from "./ServiceChart";
import ServiceTopStats from "./ServiceTopStats";

const timeset = (seconds) => {
  return DateUtils.toUnix(DateUtils.nowSubtract(seconds));
};

const timeframes = [
  { value: timeset(1800), text: "30 Minutes", set: 1 },
  { value: timeset(3600), text: "1 Hour", set: 2 },
  { value: timeset(21600), text: "6 Hours", set: 3 },
  { value: timeset(43200), text: "12 Hours", set: 4 },
  { value: timeset(86400), text: "1 Day", set: 5 },
  { value: timeset(259200), text: "3 Days", set: 6 },
  { value: timeset(604800), text: "7 Days", set: 7 },
  { value: timeset(1209600), text: "14 Days", set: 8 },
  { value: timeset(2592000), text: "1 Month", set: 9 },
  { value: timeset(7776000), text: "3 Months", set: 10 },
  { value: 0, text: "All Records" },
];

const intervals = [
  { value: "1m", text: "1/min", set: 1 },
  { value: "5m", text: "5/min", set: 2 },
  { value: "15m", text: "15/min", set: 3 },
  { value: "30m", text: "30/min", set: 4 },
  { value: "60m", text: "1/hr", set: 5 },
  { value: "180m", text: "3/hr", set: 6 },
  { value: "360m", text: "6/hr", set: 7 },
  { value: "720m", text: "12/hr", set: 8 },
  { value: "1440m", text: "1/day", set: 9 },
  { value: "4320m", text: "3/day", set: 10 },
  { value: "10080m", text: "7/day", set: 11 },
];

const stats = {
  total_failures: {
    title: "Total Failures",
    subtitle: "Last 7 Days",
    value: 0,
  },
  high_latency: {
    title: "Highest Latency",
    subtitle: "Last 7 Days",
    value: 0,
  },
  lowest_latency: {
    title: "Lowest Latency",
    subtitle: "Last 7 Days",
    value: 0,
  },
  high_ping: {
    title: "Highest Ping",
    subtitle: "Last 7 Days",
    value: 0,
  },
  low_ping: {
    title: "Lowest Ping",
    subtitle: "Last 7 Days",
    value: 0,
  },
};

const ServiceBlock = ({ service }) => {
  const history = useHistory();
  const [expanded, setExpanded] = useState(false);
  const [visible, setVisible] = useState(false);
  const [dropDownMenu, setDropDownMenu] = useState(false);
  const [intervalMenu, setIntervalMenu] = useState(false);
  const [intervalVal, setIntervalVal] = useState("60m");
  const [timeframeVal, setTimeframeVal] = useState(timeset(259200));
  // const [service, setService] = useState(null);

  const timeframepick = timeframes.find((s) => s.value === timeframeVal);

  const intervalpick = intervals.find((s) => s.value === intervalVal);

  const chartTimeframe = {
    start_time: timeframeVal,
    interval: intervalVal,
  };

  const disabled_interval = (interval) => {
    let min = timeframepick.set - interval.set - 1;
    return min >= interval.set;
  };

  const openMenu = (tm) => {
    if (tm === "interval") {
      setIntervalMenu(!intervalMenu);
      setDropDownMenu(false);
    } else if (tm === "timeframe") {
      setDropDownMenu(!dropDownMenu);
      setIntervalMenu(false);
    }
  };

  const changeInterval = (interval) => {
    setIntervalVal(interval.value);
    setIntervalMenu(false);
    setDropDownMenu(false);
  };

  const changeTimeframe = (timeframe) => {
    setTimeframeVal(timeframe.value);
    setIntervalMenu(false);
    setDropDownMenu(false);
  };

  const handlesetService = () => {
    // setService(service);
    history.push("/service/" + service.id, {
      props: { service: service },
    });
  };

  const visibleChart = (isVisible, entry) => {
    if (isVisible && !visible) {
      setVisible(true);
    }
  };

  return (
    <div className="mb-md-4 mb-4">
      <div className={`card index-chart ${expanded ? "expanded-service" : ""}`}>
        <div className="card-body">
          <div className="col-12">
            <h4 className="mt-2">
              <span
                className="d-inline-block text-truncate font-4"
                style={{ maxWidth: "65vw" }}
                // to={serviceLink(service)}
                // in_service={service}
              >
                {service.name}
              </span>
              <span
                className={`badge float-right ${
                  service.online ? "bg-success" : "bg-danger"
                }`}
              >
                {service.online ? "ONLINE" : "OFFLINE"}
              </span>
            </h4>

            <ServiceTopStats service={service} />
          </div>
        </div>

        {/* <div
          // v-observe-visibility="{ callback: visibleChart, throttle: 200 }"
          className="chart-container"
        >
          <ServiceChart
            service={service}
            visible={visible}
            chartTimeframe={chartTimeframe}
          />
        </div> */}

        <div
          className={`row lower_canvas full-col-12 text-white ${
            service.online ? "bg-success" : "bg-danger"
          }`}
        >
          <div className="col-md-10 col-6">
            <div className={`dropup ${dropDownMenu ? "show" : ""}`}>
              <button
                style={{ fontSize: "10pt" }}
                onClick={() => openMenu("timeframe")}
                type="button"
                className="col-4 float-left btn btn-sm float-right btn-block text-white dropdown-toggle service_scale pr-2"
              >
                {timeframepick.text}
              </button>
              <div
                className={`service-tm-menu ${!dropDownMenu ? "d-none" : ""}`}
              >
                {timeframes.map((timeframe, i) => {
                  return (
                    <a
                      href="#"
                      onClick={() => changeTimeframe(timeframe)}
                      className={`dropdown-item ${
                        timeframepick === timeframe ? "active" : ""
                      }`}
                      key={i}
                    >
                      {timeframe.text}
                    </a>
                  );
                })}
              </div>
            </div>

            <div className={`dropup ${intervalMenu ? "show" : ""}`}>
              <button
                style={{ fontSize: "10pt" }}
                onClick={() => openMenu("interval")}
                type="button"
                className="col-4 float-left btn btn-sm float-right btn-block text-white dropdown-toggle service_scale pr-2"
              >
                {intervalpick.text}
              </button>
              <div
                className={`service-tm-menu ${!intervalMenu ? "d-none" : ""}`}
              >
                {intervals.map((interval, i) => {
                  return (
                    <a
                      href="#"
                      onClick={() => changeInterval(interval)}
                      className={`dropdown-item ${
                        intervalpick === interval ? "active" : ""
                      }`}
                      disabled={disabled_interval(interval)}
                      key={i}
                    >
                      {interval.text}
                    </a>
                  );
                })}
              </div>

              <span className="d-none float-left d-md-inline">
                {DateUtils.smallText(service)}
              </span>
            </div>
          </div>

          {/* <div className="col-md-2 col-6 float-right">
            <button
              onClick={() => setExpanded(!expanded)}
              // onClick={handlesetService}
              className={`btn btn-sm float-right dyn-dark text-white ${
                service.online ? "bg-success" : "bg-danger"
              }`}
            >
              {langs("view")}
            </button>
          </div> */}
        </div>
      </div>
    </div>
  );
};

export default ServiceBlock;
